image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest


Deploys-to-s3:
    script:
        - aws --version
        - aws deploy push --application-name wp-prod-g1 --s3-location s3://s3-groupe1/toto --source ./
        - aws deploy create-deployment --application-name wp-prod-g1 --deployment-group-name production-g1 --s3-location bucket=s3-groupe1,key=/toto --region eu-north-1