image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest

stages:
    - push
    - deploy

variables:
    AWS_ACCESS_KEY_ID: '${DYLAN_AWS_ACCESS_KEY_ID}'
    AWS_SECRET_ACCESS_KEY: '${DYLAN_AWS_SECRET_ACCESS_KEY}'


Push-to-s3:
    stage: push
    script:
        - cp ./docker_images/srv_php/install_wp-cli.sh ./aws/scripts/install_wp-cli.sh
        - sed -i -e '/exec "$@"/d' ./aws/scripts/install_wp-cli.sh
        - aws --version
        - aws deploy push --application-name wp-prod-g1 --s3-location s3://s3-groupe1/bundle.zip --source ./aws
    only:
        - dylan

Deploy-to-ec2:
    stage: deploy
    script:
        - aws --version
        - aws deploy create-deployment --application-name wp-prod-g1 --deployment-group-name production-g1 --s3-location bucket=s3-groupe1,bundleType=zip,key=bundle.zip --region eu-north-1
    only:
        - dylan