image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest


Deploys-to-s3:
    script:
        - aws --version
        - aws deploy push --application-name wp-prod-g1 --s3-location s3://s3-groupe1/toto --source ./