version: '3'

services:
    mysql:
      image: mysql:8
      container_name: srv_mysql
      volumes:
        - mysql_data:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
            
    nginx:
      depends_on:
        - php
      image: nginx
      container_name: srv_wordpress
      ports:
        - "8080:80"
      volumes:
        - wordpress_data:/var/www/html
        - ./config/srv_wordpress/nginx.conf:/etc/nginx/nginx.conf
      restart: always
    
    php:
      depends_on:
        - mysql
      build:
        context: ./docker_images/srv_php/
      container_name: srv_php
      volumes:
        - wordpress_data:/var/www/html
      restart: always
      environment:
        MYSQL_HOST: ${MYSQL_HOST}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_TABLE_PREFIX: ${MYSQL_TABLE_PREFIX}
        WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
        WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
        WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
        WORDPRESS_TITLE: ${WORDPRESS_TITLE}
        WORDPRESS_URL: ${WORDPRESS_URL}

volumes:
  mysql_data:
  wordpress_data: