version: 0.0
os: linux

files:
  - source: scripts/install_wp-cli.sh 
    destination: /var/www/html

hooks:

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/set_env.sh
      timeout: 300
      runas: root
    - location: scripts/install_wp-cli.sh
      timeout: 300
      runas: www-data

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root